### ISSUE TITLE
Logout/Login as different user

### ISSUE THREAD

**Issue by helmuttheis** [michael79bxl/cordova-plugin-auth-dialog#1]
Hallo Michael,

I would like to use your plugin in a Cordova app for Android, iOS and Windows 8.1.
But I need the logout functionality too. 
Could you add a function to clear the cached credentials?

Best regards,

Helmut Theis

**Comment by michael79bxl** [comment]
Guten abend Helmut ;-)

This is not the classic behavior on most browsers.

NB: InAppBrowser is only supported on iOS.

I made a test for iOS, it builds, but you'll have give it a try and give me some feedback so I can help you.

If it works, I'll see how to implement it for Android and Windows phone.

Tschüss,

Michael

**Comment by michael79bxl** [comment]
https://github.com/michael79bxl/cordova-plugin-auth-dialog/issues/1#issuecomment-135881084

**Comment by helmuttheis** [comment]
Hallo Michael, (ou bonjour?)

 

Thank you very much for your response.

 

I am currently involved in another project, so I won’t be able to investigate this further, at least for the next 2 weeks.

 

My primary development environment is Visual Studio and I am working with Windows and Android.

So testing with iOS requires additional configuration.

 

I did some further testing with Windows, and there seems to be an underlying credential caching other than the Windows Credentials Manager.

I was not able to clear the cache, not even by uninstalling the app.

 

So implementing this feature may not be possible at all.

 

When I return to this development and if I find a solution I will describe it here.

 

 

 

Gruß,

 

Helmut

 

Von: michael79bxl [mailto:notifications@github.com] 
Gesendet: Freitag, 28. August 2015 22:30
An: michael79bxl/cordova-plugin-auth-dialog <cordova-plugin-auth-dialog@noreply.github.com>
Cc: helmuttheis <helmut.theis@hypermediasystems.de>
Betreff: Re: [cordova-plugin-auth-dialog] Logout/Login as different user (#1)

 

Guten abend Helmut ;-)

This is not the classic behavior on most browsers.

NB: InAppBrowser is only supported on iOS.

I made a test for iOS, it builds, but you'll have give it a try and give me some feedback so I can help you.

If it works, I'll see how to implement it for Android and Windows phone.

Tschüss,

Michael

**Comment by michael79bxl** [comment]
Are you using the plugin for XHR ?

It is said on various forums that clearing credentials on Android is also NOT working due to a bug, still not resolved in Android 5.

Passing invalid credentials might trigger a new login request and maybe it will logout ?

**Comment by alexsherekin** [comment]
@michael79bxl is it possible to force logout on Android anyhow?
In my use case users connect to MS Dynamics with http base oauth and after the first successful login they are not able to switch any more. Only the app restart helps.
It would be nice to have in Android version the same functionality like in iOS version to manually trigger logout.

**Comment by wlkoo** [comment]
Is there a workaround to logout a user for Android?

**Comment by michael79bxl** [comment]
Nope. Sorry.
