### ISSUE TITLE
Adobe phonegap gradle build fails

### ISSUE THREAD

**Issue by acoy** [michael79bxl/cordova-plugin-auth-dialog#3]
Adobe phonegap  build fail with gradle, npm package not updated?

**Comment by michael79bxl** [comment]
No. Sorry. You need to force an older Phonegap version.
I will take a loot at M$ updates to see if it supports gradle.

**Comment by acoy** [comment]
Phonegap gradle build fails with this https://github.com/MSOpenTech/cordova-plugin-auth-dialog/issues/5

**Comment by michael79bxl** [comment]
Just updated the release and published to npm. Does it work now?

**Comment by acoy** [comment]
Worked like charm. Thank you  and Merry Christmas from Finland :)
